version: 2.1
jobs:
  main-test:
    docker:
    - image: circleci/php:7.2
    - image: google/cloud-sdk:240.0.0-alpine
      command: [gcloud, beta, emulators, datastore, start, '--project=laravel-datastore-auth-test', '--host-port', '0.0.0.0:8081']
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-composer-{{ checksum "composer.lock" }}
    - run: composer install
    - save_cache:
        paths:
          - ./vendor
        key: v1-composer-{{ checksum "composer.lock" }}
    - run: |
        sudo apt update
        sudo apt install -y wait-for-it
        wait-for-it localhost:8081
    - run: vendor/bin/phpunit
    - run: |
        curl -o codecov https://codecov.io/bash
        chmod +x codecov
    - run: ./codecov -f build/clover.xml
  test:
    parameters:
      php-version:
        type: string
      composer_arguments:
        type: string
        default: ""
    docker:
    - image: circleci/php:<< parameters.php-version >>
    - image: google/cloud-sdk:240.0.0-alpine
      command: [gcloud, beta, emulators, datastore, start, '--project=laravel-datastore-auth-test', '--host-port', '0.0.0.0:8081']
    working_directory: ~/repo
    steps:
    - checkout
    - run: composer update << parameters.composer_arguments >>
    - run: |
        sudo apt update
        sudo apt install -y wait-for-it
        wait-for-it localhost:8081
    - run: vendor/bin/phpunit
workflows:
  build:
    jobs:
      - "main-test"
      - test:
          name: "test-php7.1"
          php-version: "7.1"
      - test:
          name: "test-php7.2"
          php-version: "7.2"
      - test:
          name: "test-php7.1-prefer_lowest"
          php-version: "7.1"
          composer_arguments: "--prefer-lowest"
      - test:
          name: "test-php7.2-prefer_lowest"
          php-version: "7.2"
          composer_arguments: "--prefer-lowest"
