version: 2.1
jobs:
  main-test:
    docker:
    - image: circleci/php:7.4
    - image: google/cloud-sdk:242.0.0
      command: [gcloud, beta, emulators, datastore, start, '--project=laravel-datastore-auth-test', '--host-port=0.0.0.0:8081', '-q', '--consistency=1.0']
    working_directory: ~/repo
    steps:
    - checkout
    - run: composer install
    - run: vendor/bin/phpunit
    - run: |
        curl -o codecov https://codecov.io/bash
        chmod +x codecov
    - run: ./codecov -f build/clover.xml
  test:
    parameters:
      php-version:
        type: string
      composer_arguments:
        type: string
        default: ""
    docker:
    - image: circleci/php:<< parameters.php-version >>
    - image: google/cloud-sdk:242.0.0
      command: [gcloud, beta, emulators, datastore, start, '--project=laravel-datastore-auth-test', '--host-port=0.0.0.0:8081', '-q', '--consistency=1.0']
    working_directory: ~/repo
    steps:
    - checkout
    - run: composer update << parameters.composer_arguments >>
    - run: vendor/bin/phpunit
workflows:
  build:
    jobs:
      - "main-test"
      - test:
          name: "test-php7.1"
          php-version: "7.1"
      - test:
          name: "test-php7.2"
          php-version: "7.2"
      - test:
          name: "test-php7.3"
          php-version: "7.3"
      - test:
          name: "test-php7.4"
          php-version: "7.4"
      - test:
          name: "test-php7.1-prefer_lowest"
          php-version: "7.1"
          composer_arguments: "--prefer-lowest"
      - test:
          name: "test-php7.2-prefer_lowest"
          php-version: "7.2"
          composer_arguments: "--prefer-lowest"
      - test:
          name: "test-php7.3-prefer_lowest"
          php-version: "7.3"
          composer_arguments: "--prefer-lowest"
      - test:
          name: "test-php7.4-prefer_lowest"
          php-version: "7.4"
          composer_arguments: "--prefer-lowest"
